[package]
name = "resolve-nested-genotypes"
version = "0.1.0"
authors = ["Glenn Hickey <glenn.hickey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vcf = "0.5.0"
flate2 = "1.0.22"
